# Generated by Django 3.2.1 on 2021-05-23 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DisciplineMacroContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macro_content', models.CharField(max_length=255)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutes.discipline', verbose_name='discipline')),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DisciplineMicroContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('micro_content', models.CharField(max_length=255)),
                ('macro_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutes.disciplinemacrocontent', verbose_name='macro_content')),
            ],
        ),
        migrations.AddField(
            model_name='discipline',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutes.institute', verbose_name='institute'),
        ),
    ]
