version: "3"

services:
    django:
        build: .
        restart: on-failure
        container_name: django
        command: bash -rc "python intento/manage.py makemigrations &&
                           python intento/manage.py migrate &&
                           gunicorn --limit-request-line 8190 --workers=3
                           --chdir /usr/src/app/intento wsgi:application --bind 0.0.0.0:8000"
        volumes:
            - .:/usr/src/app
        expose:
            - 8000
        env_file:
            - ./.env
        depends_on:
            - pgdb
    pgdb:
        image: postgres
        restart: on-failure
        container_name: pgdb
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
    nginx:
        build:
          context: .
          dockerfile: ./nginx/Dockerfile
        image: nginx
        restart: unless-stopped
        volumes:
          - /etc/letsencrypt/archive/apwebdev.xyz:/etc/nginx/certs
          - ./intento/static:/etc/nginx/static
        ports:
          - 80:80
          - 443:443
        depends_on:
          - django
volumes:
  postgres_data:
