# Generated by Django 3.2.2 on 2021-05-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='permissions',
            field=models.CharField(choices=[('AD', 'Administrador(a)'), ('VD', 'Validador(a) de Questões'), ('TC', 'Professor(a)')], default='TC', max_length=2),
            preserve_default=False,
        ),
    ]
