# Generated by Django 3.2.1 on 2021-05-23 21:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('EZ', 'Fácil'), ('IM', 'Intermediário'), ('HD', 'Difícil')], max_length=2)),
                ('bloom_taxonomy', models.CharField(choices=[('KW', 'Conhecimento'), ('CP', 'Compreensão'), ('AP', 'Aplicação'), ('AN', 'Análise'), ('SY', 'Síntese'), ('AV', 'Avaliação')], max_length=2)),
                ('question_information', models.CharField(choices=[('HT', 'Contém Tabela'), ('HG', 'Contém Gráfico'), ('HI', 'Contém Imagem'), ('TO', 'Somente Texto')], max_length=2)),
                ('correct_answer', models.CharField(choices=[('A', 'Alternativa A'), ('B', 'Alternativa B'), ('C', 'Alternativa C'), ('D', 'Alternativa D'), ('E', 'Alternativa E')], max_length=1)),
                ('a_justification', django_quill.fields.QuillField(blank=True)),
                ('b_justification', django_quill.fields.QuillField(blank=True)),
                ('c_justification', django_quill.fields.QuillField(blank=True)),
                ('d_justification', django_quill.fields.QuillField(blank=True)),
                ('e_justification', django_quill.fields.QuillField(blank=True)),
                ('revision_approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_by_order', models.IntegerField()),
                ('question_type', models.CharField(choices=[('IA', 'Afirmação Incompleta'), ('AR', 'Asserção-Razão'), ('CA', 'Associação de Colunas'), ('GP', 'Lacuna'), ('CM', 'Múltipla Escolha Complexa'), ('SM', 'Múltipla Escolha Simples'), ('SR', 'Seriação'), ('TF', 'Verdadeiro ou Falso')], max_length=2)),
                ('base_text', django_quill.fields.QuillField()),
                ('bibliographic_reference', models.CharField(max_length=1000)),
                ('question_statement', django_quill.fields.QuillField()),
                ('answer_A', django_quill.fields.QuillField()),
                ('answer_B', django_quill.fields.QuillField()),
                ('answer_C', django_quill.fields.QuillField()),
                ('answer_D', django_quill.fields.QuillField()),
                ('answer_E', django_quill.fields.QuillField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('order_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutes.discipline', verbose_name='discipline')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutes.institute', verbose_name='institute')),
                ('macro_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutes.disciplinemacrocontent', verbose_name='macro_content')),
                ('micro_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutes.disciplinemicrocontent', verbose_name='micro_content')),
            ],
        ),
    ]
