# Generated by Django 3.2.3 on 2021-06-05 22:26

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210603_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='base_text_2',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='base_text_3',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='bibliographic_reference_2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='bibliographic_reference_3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
