# Generated by Django 3.2.4 on 2021-06-06 19:13

from django.db import migrations, models
import django_quill.fields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('orders', '0004_auto_20210605_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='a_justification',
            field=django_quill.fields.QuillField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='b_justification',
            field=django_quill.fields.QuillField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='bloom_taxonomy',
            field=models.CharField(choices=[('KW', 'Conhecimento'), ('CP', 'Compreensão'), ('AP', 'Aplicação'), ('AN', 'Análise'), ('SY', 'Síntese'), ('AV', 'Avaliação')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='c_justification',
            field=django_quill.fields.QuillField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'Alternativa A'), ('B', 'Alternativa B'), ('C', 'Alternativa C'), ('D', 'Alternativa D'), ('E', 'Alternativa E')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='d_justification',
            field=django_quill.fields.QuillField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('EZ', 'Fácil'), ('IM', 'Intermediário'), ('HD', 'Difícil')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='e_justification',
            field=django_quill.fields.QuillField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_information',
            field=models.CharField(choices=[('HT', 'Contém Tabela'), ('HG', 'Contém Gráfico'), ('HI', 'Contém Imagem'), ('TO', 'Somente Texto')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='revision_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
