# Generated by Django 3.2.4 on 2021-06-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210606_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='general_justification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
