# Generated by Django 3.2.1 on 2021-05-06 00:47

from django.db import migrations, models
import django.db.models.deletion
import vditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('IA', 'Afirmação Incompleta'), ('AR', 'Asserção-Razão'), ('CA', 'Associação de Colunas'), ('GP', 'Lacuna'), ('CM', 'Múltipla Escolha Complexa'), ('SM', 'Múltipla Escolha Simples'), ('SR', 'Seriação'), ('TF', 'Verdadeiro ou Falso')], max_length=2)),
                ('base_text', vditor.fields.VditorTextField()),
                ('bibliographic_reference', models.CharField(max_length=1000)),
                ('question_statement', vditor.fields.VditorTextField()),
                ('answer_A', vditor.fields.VditorTextField()),
                ('answer_B', vditor.fields.VditorTextField()),
                ('answer_C', vditor.fields.VditorTextField()),
                ('answer_D', vditor.fields.VditorTextField()),
                ('answer_E', vditor.fields.VditorTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('EZ', 'Fácil'), ('IM', 'Intermediário'), ('HD', 'Difícil')], max_length=2)),
                ('bloom_taxonomy', models.CharField(choices=[('KW', 'Conhecimento'), ('CP', 'Compreensão'), ('AP', 'Aplicação'), ('AN', 'Análise'), ('SY', 'Síntese'), ('AV', 'Avaliação')], max_length=2)),
                ('question_information', models.CharField(choices=[('HT', 'Contém Tabela'), ('HG', 'Contém Gráfico'), ('HI', 'Contém Imagem'), ('TO', 'Somente Texto')], max_length=2)),
                ('correct_answer', models.CharField(choices=[('A', 'Alternativa A'), ('B', 'Alternativa B'), ('C', 'Alternativa C'), ('D', 'Alternativa D'), ('E', 'Alternativa E')], max_length=1)),
                ('a_justification', models.TextField()),
                ('b_justification', models.TextField()),
                ('c_justification', models.TextField()),
                ('d_justification', models.TextField()),
                ('e_justification', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.questions')),
            ],
        ),
    ]
