# Generated by Django 3.2.2 on 2021-05-07 14:36

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='a_justification',
            field=django_quill.fields.QuillField(blank=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='b_justification',
            field=django_quill.fields.QuillField(blank=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='c_justification',
            field=django_quill.fields.QuillField(blank=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='d_justification',
            field=django_quill.fields.QuillField(blank=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='e_justification',
            field=django_quill.fields.QuillField(blank=True),
        ),
    ]
