# Generated by Django 3.2.2 on 2021-05-13 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_questionorder_question_quantity'),
        ('dashboard', '0003_auto_20210513_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.questionorder', verbose_name='question'),
        ),
    ]
