# Generated by Django 3.2.2 on 2021-05-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_question_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='tag',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
