# Generated by Django 3.2.2 on 2021-05-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_answer_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='id_by_order',
            field=models.IntegerField(null=True),
        ),
    ]
