# Generated by Django 3.2.3 on 2021-05-14 21:36

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('dashboard', '0007_question_id_by_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='tag',
        ),
        migrations.AddField(
            model_name='answer',
            name='tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
