# Generated by Django 3.2.3 on 2021-05-16 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_questionorder_question_quantity'),
        ('dashboard', '0008_auto_20210514_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.question', verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.questionorder', verbose_name='questionorder'),
        ),
    ]
