# Generated by Django 3.2.3 on 2021-05-16 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_questionorder_question_quantity'),
        ('dashboard', '0009_auto_20210516_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionorder', to='courses.questionorder', verbose_name='questionorder'),
        ),
    ]
