# Generated by Django 3.2.2 on 2021-05-13 00:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0002_profile_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=255)),
                ('macro_content', models.CharField(max_length=255)),
                ('micro_content', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('order_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.discipline', verbose_name='Discipline')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.institute', verbose_name='Institute')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.profile', verbose_name='Teacher')),
            ],
        ),
    ]
